# Demonstrating all Arithmetic Operators... ( integer number)
a = int(input("Enter your first number (a): "))
b = int(input("Enter your second number (b): "))
c = int(input("Enter your third number (c): "))

print("Modulus / Remainder (a % b % c):", a % b % c)
print("Exponentiation / Power (a ** b ** c):", a ** b ** c)
print("Normal Division (a / b / c):", a / b / c)
print("Floor Division (a // b // c):", a // b // c)
print("Multiplication (a * b * c):", a * b * c)
print("Addition (a + b + c):", a + b + c)
print("Subtraction (a - b - c):", a - b - c)

# Demonstrating all Arithmetic Operators.. (float/ decimal number)
a = float(input("Enter your first number (a): "))
b = float(input("Enter your second number (b): "))
c = float(input("Enter your third number (c): "))

print("Modulus / Remainder (a % b % c):", a % b % c)
print("Exponentiation / Power (a ** b ** c):", a ** b ** c)
print("Normal Division (a / b / c):", a / b / c)
print("Floor Division (a // b // c):", a // b // c)
print("Multiplication (a * b * c):", a * b * c)
print("Addition (a + b + c):", a + b + c)
print("Subtraction (a - b - c):", a - b - c)
